# Generated by Django 3.2.4 on 2021-06-10 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210610_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_name',
            field=models.CharField(default=datetime.datetime(2021, 6, 10, 13, 8, 55, 956293, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(default=datetime.datetime(2021, 6, 10, 13, 9, 12, 320017, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
