# Generated by Django 3.2.4 on 2021-06-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210605_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
